apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-vm
spec:
  generators:
  - list:
      elements:
      - cluster: cs00167-we-02-aks
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: "demo-vm"
    spec:
      project: default
      source:
        repoURL: https://github.com/Techwidot/kubevirt.git
        targetRevision: HEAD
        path: "applicationsets/demo-vm/kustomize/dev"
        kustomize:
          commonAnnotations:
            managed-cluster: "{{nameNormalized}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-virtualization-os-images
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
